# Generated by Django 5.1.5 on 2025-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownload',
            name='temp_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
